export const AUTH_FORM = {
  SIGNIN: {
    EMAIL_LABEL: 'System.out.print("Email:");',
    EMAIL_PLACEHOLDER: "hello@world.com",
    PASSWORD_LABEL: 'System.out.print("Password:");',
    PASSWORD_PLACEHOLDER: "••••••••••••",
    FORGOT_PASSWORD_TEXT: "Forgot password?",
    FORGOT_PASSWORD_HREF: "#",
    SUBMIT_TEXT: "Connect",
  },
  SIGNUP: {
    FIRST_NAME_LABEL: 'System.out.print("First Name:");',
    FIRST_NAME_PLACEHOLDER: "Abdullah",
    LAST_NAME_LABEL: 'System.out.print("Last Name:");',
    LAST_NAME_PLACEHOLDER: "Tanveer",
    EMAIL_LABEL: 'System.out.print("Email:");',
    EMAIL_PLACEHOLDER: "hello@world.com",
    PASSWORD_LABEL: 'System.out.print("Password:");',
    PASSWORD_PLACEHOLDER: "••••••••••••",
    AGE_LABEL: 'System.out.print("Age:");',
    AGE_PLACEHOLDER: "22",
    GENDER_LABEL: 'System.out.print("Gender:");',
    GENDER_OPTIONS: [
      { value: "", label: "Select gender" },
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
      { value: "other", label: "Other" },
    ],
    PHOTO_URL_LABEL: 'System.out.print("Photo URL:");',
    PHOTO_URL_PLACEHOLDER: "https://example.com/profile.jpg",
    DESCRIPTION_LABEL: 'System.out.print("Description:");',
    DESCRIPTION_PLACEHOLDER: "Full stack developer and MERN stack learner",
    INTERESTS_LABEL: 'System.out.print("Interests:");',
    INTERESTS_PLACEHOLDER: "Coding, Cricket, Traveling",
    LOCATION_LABEL: 'System.out.print("Location:");',
    LOCATION_PLACEHOLDER: "Lahore, Pakistan",
    SUBMIT_TEXT: "Create Account",
  },
} as const;
