export const AUTH_FORM = {
  SIGNIN: {
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "you@example.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••••••",
    FORGOT_PASSWORD_TEXT: "Forgot password?",
    FORGOT_PASSWORD_HREF: "#",
    SUBMIT_TEXT: "Connect",
  },
  SIGNUP: {
    FIRST_NAME_LABEL: "First Name",
    FIRST_NAME_PLACEHOLDER: "John",
    LAST_NAME_LABEL: "Last Name",
    LAST_NAME_PLACEHOLDER: "Doe",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "you@example.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••••••",
    AGE_LABEL: "Age",
    AGE_PLACEHOLDER: "25",
    GENDER_LABEL: "Gender",
    GENDER_OPTIONS: [
      { value: "", label: "Select gender" },
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
      { value: "other", label: "Other" },
    ],
    PHOTO_URL_LABEL: "Photo",
    PHOTO_URL_PLACEHOLDER: "https://example.com/photo.jpg",
    DESCRIPTION_LABEL: "About You",
    DESCRIPTION_PLACEHOLDER: "Tell us a bit about yourself...",
    INTERESTS_LABEL: "Interests",
    INTERESTS_PLACEHOLDER: "Select your interests",
    LOCATION_LABEL: "Location",
    LOCATION_PLACEHOLDER: "Your city, country",
    SUBMIT_TEXT: "Create Account",
  },
} as const;
